---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first }}/cert.pem
  register: letsencrypt_cert

- name: copy CF API scripts
  template:
    src: "{{ item }}.j2"
    dest: /usr/local/sbin/{{ item }}
    mode: 0755
  with_items:
    - authenticator.sh
    - cleanup.sh

- name: Generate new certificate if one doesn't exist.
  shell: "{{ certbot_create_command_dns_challenge }}"
  when: not letsencrypt_cert.stat.exists
